# Generated by Django 4.2 on 2024-10-17 13:26

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='additional_inf',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Additional Information'),
        ),
        migrations.AddField(
            model_name='product',
            name='main_inf',
            field=django_ckeditor_5.fields.CKEditor5Field(default=1, verbose_name='Main Information'),
            preserve_default=False,
        ),
    ]
