# Generated by Django 4.2 on 2024-10-17 13:28

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_additional_inf_product_main_inf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='additional_inf',
        ),
        migrations.RemoveField(
            model_name='product',
            name='main_inf',
        ),
        migrations.AddField(
            model_name='product',
            name='short_inf',
            field=django_ckeditor_5.fields.CKEditor5Field(default=42, verbose_name='Short Information'),
            preserve_default=False,
        ),
    ]
