# Generated by Django 4.2 on 2024-10-17 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_product_additional_inf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='life',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.CharField(default='10kg in stock', max_length=100),
        ),
    ]
